language: ruby
rvm:
  - 2.1.7
notifications:
  slack: titansoft:EXkKV4uNe8HpI4pPWauilOs6
before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- bundle exec rake db:test:prepare
deploy:
  provider: heroku
  api_key: cc53536a-6c99-4b5a-ab56-615f5a32fdd8
  run: "rake db:migrate"
